### ISSUE TITLE
[Structure] Structure Update

### ISSUE THREAD

**Issue by poon-bmk** [HMSConnect/hms-widget-sdk#19]
**Updates on Project Specifications**
	From the previous report, the structure of the project has been updated, with the link attached below.
https://docs.google.com/document/d/1-Vy2uB27GiPXaQTR0Ya_-xjec0fG-9-pH3C9uSVIsVA/

**Backend**
1. For clients to render correct data format (SFHIR/HMS Connect), we would like to confirm which approach should be used.
          a. Server explicitly inform client. e.g. special HTTP Header
          b. Client try to auto-detect the format. e.g. find some unique indicator
	Assumption: Client may try to specify required format, but in some situations, the server might not be able to honor the request.

**Frontend**

1. For hms-data that have multiple sets, which set of data that we should use for search or display? Such as patient’s names for the SFHIR standard that have 2 sets, Official and Maiden. I suggest following the patient-browser for display hms-data.
2. We will add Typescript for React.
3. We have to add the folder structure.
           app/services  →  a service to fetch data from the server.
           app/hooks  →  sometimes we use a hook to implement a stateful function.
4. Are we understand component structure correct?
           /base →  as same as components in Material-UI library (Stateless) 
                    such as Button, Grid, Input
           /template → many bases combined (Stateless)
                    such as Searchbar
           /widget →  many templates combined (Stateful)
                    such as PatientSearch

**Comment by HMSConnect** [comment]
From your question :

**Backend**

> For clients to render correct data format (SFHIR/HMS Connect), we would like to confirm which approach should be used.
a. Server explicitly inform client. e.g. special HTTP Header
b. Client try to auto-detect the format. e.g. find some unique indicator
Assumption: Client may try to specify required format, but in some situations, the server might not be able to honor the request.

_For my opinion_:
client should be stateless and server side should handle a little task. So I suggest you to implement middleware for parsing/compiling the data object. The middleware can be implemented in frontend/backend upon your design.

**Frontend**

For hms-data that have multiple sets, which set of data that we should use for search or display? Such as patient’s names for the SFHIR standard that have 2 sets, Official and Maiden.

> Should support both formats

I suggest following the patient-browser for display hms-data.

> I'm not sure what **patient-browser** is...

We will add Typescript for React.

> OK krub, please don't forget add some comment in you source code.

We have to add the folder structure.
app/services → a service to fetch data from the server.
app/hooks → sometimes we use a hook to implement a stateful function.

> OK krub. If you can design middleware to parse/compile the data object, please attach it into this topic.

Are we understand component structure correct?
/base → as same as components in Material-UI library (Stateless)
such as Button, Grid, Input
/template → many bases combined (Stateless)
such as Searchbar
/widget → many templates combined (Stateful)
such as PatientSearch

> OK krub.
