### ISSUE TITLE
[Q&A] The issue about "ผลการวินิจฉัย" key in each encounter

### ISSUE THREAD

**Issue by HMSConnect** [HMSConnect/hms-widget-sdk#23]
Ref meeting at 13 Dec 2019, your mention about "ผลการวินิจฉัย" key in each encounter.
https://www.dropbox.com/s/8ri17l1nihxax4b/issue-diagnosis-key.png?dl=0

**Comment by HMSConnect** [comment]
After discussion, "ผลการวินิจฉัย" key is diagnosis report. You should call via endpoint name :
- In SmartFHIR : /DiagnosticReport
  By passing the encounter ID (current ID) to the endpoint, ex. https://r3.smarthealthit.org/DiagnosticReport/afb695ea-8ffd-428c-b389-739707072380
- In HMSConnect : /v1/persist/Diagnosis
  Ex. the data object
```json
{
    "message": "Diagnosis has been executed.",
    "data": [
        {
            "resourceType": "Diagnosis",
            "hn": “XX-XX-XXXXXX”,
            "en": “TXX-XX-XXXXXXX”,
            "clinicalStatus": "active",
            "verificationStatus": "confirmed",
            "asserter": “XXXXXXXXX”,
            "assertedDate": "2019-11-25T00:00:00",
            "identifier": [
                {
                    "type": "",
                    "value": “”
                }
            ],
            "severity": {
                "code": null,
                "display": null
            },
            "bodySite": {
                "code": null,
                "display": null
            },
            "code": [
                {
                    "code": "",
                    "display": "",
                    "system": "",
                    "onsetDatetime": null,
                    "onsetDuration": null,
                    "onsetUnit": null
                }
            ],
            "category": [
                {
                    "code": "",
                    "display": ""
                }
            ],
            "comments": [],
            "organization": {
                "codeNumber": "",
                "codeName": "",
                "name": null,
                "latitude": null,
                "longitude": null
            },
            "created": "2019-12-16T10:04:21",
            "updated": ""
        }
    ]
}
```

Note: For HMSConnect, it quite different and unofficial. Now you can focus on SmartFHIR first.

**Comment by patharanordev** [comment]
@new-bmk , 

Normally our flow is:
patient -> encounter -> demographic(allergy -> diagnosis -> observation)

if you got encounter ID, you can find allergy, diagnosis and observation by using encounter ID. So "ผลการวินิจฉัย", you can use the encounter ID to find "**diagnosis**" via `https://r3.smarthealthit.org/DiagnosticReport/ENCOUNTER_ID`

Note: 
- This issue related encounter timeline. If you finish this issue, you can close encounter issue.
- "->" means "using ID of left node to find right node"
