### ISSUE TITLE
Can't request  `Care Plan` domain resource

### ISSUE THREAD

**Issue by new-bmk** [HMSConnect/hms-widget-sdk#35]
**Describe the bug**
Can't request `Care Plan` domain resource but it exists document from the link below.
https://hms-gateway-001.gitbook.io/openhealth-api/hms-standard/data-template-v.2/care-plan

**Comment by HMSConnect** [comment]
@new-bmk , the schema didn't provide to sandbox yet. I will add it and inform you soon.

**Comment by HMSConnect** [comment]
@new-bmk , I added 2-domain resources below:
1. Care plan - in URL request, please using `careplan`.
2. Medication dispense - in URL request, please using `medicationdispense`.

and updated GitBook (https://hms-gateway-001.gitbook.io/openhealth-api/usage/ui-data-mapping)
by removing "domain resource name" in column "Field"
