### ISSUE TITLE
Diastolic and Systolic in Vital-Sign can multiple fields?

### ISSUE THREAD

**Issue by new-bmk** [HMSConnect/hms-widget-sdk#38]
ตอนนี้ลอง query โดยหา Diastolic and Systolic ผ่าน name ของ resource Vital-Sign โดยใช้ชื่อ `BP` 
ผลปรากฏมี group ชื่อ ผลลัพธ์ดังนี้
1. Diastolic BP และ Systolic BP
และ
2. Diastolic BP(PED) และ Systolic BP(PED) 

**คำถาม** มีโอกาสที่จะได้ค่ามา 4 ค่าพร้อมกันไหม ซึ่งก็คือ Diastolic BP, Systolic BP, Diastolic BP(PED) และ Systolic BP(PED) หากมีโอกาส เราจะเลือกค่าคู่ไหนมาแสดงครับ

**Comment by HMSConnect** [comment]
@new-bmk , after discussed with team, Diastolic BP and Systolic BP have 2-parts:
1.Diastolic BP and Systolic BP for adult (ผู้ใหญ่)
2.Diastolic BP(PED) and Systolic BP(PED) for juvenile (เด็ก)

So answer your question is : you will see only couple of (**Diastolic BP and Systolic BP**) or (**Diastolic BP(PED) and Systolic BP(PED)**)
