### ISSUE TITLE
No example of Heart rate in vital-sign?

### ISSUE THREAD

**Issue by new-bmk** [HMSConnect/hms-widget-sdk#40]
**Describe the bug**
ลองค้นหาผ่านโดยใช้ https://hms-gateway-001.gitbook.io/openhealth-api/usage/ui-data-mapping#heart-rate อ้างอิง
ไม่มีข้อมูลครับ

**Comment by HMSConnect** [comment]
@new-bmk , please try : 

name = "Heart rate".
