### ISSUE TITLE
medicationdispense schema.ResourceType is null

### ISSUE THREAD

**Issue by kopai-bmk** [HMSConnect/hms-widget-sdk#41]
**Describe the bug**
request to 'medicationdispense service' but resived data with schema.resourceType: null

**Comment by HMSConnect** [comment]
@kopai-bmk , your question same as 'careplan', I'm not sure I understand your point or not.
But I got expected result, please refer to the image below:
https://www.dropbox.com/s/l95fduhkcqiqyge/medicationdispense-schema-is-null.png?dl=0

**Comment by HMSConnect** [comment]
@kopai-bmk , I have fixed the issue on schema version "2.4.32". Please help check it again.
