### ISSUE TITLE
cannot request load from patient

### ISSUE THREAD

**Issue by kopai-bmk** [HMSConnect/hms-widget-sdk#42]
I try to request searching by patientId from domain 'patient' but  failed with status code 404.
my search id is 'MOCK-54569-4443'

Refer to the link below:
https://hms-gateway-001.gitbook.io/openhealth-api/usage/restful-api#searching-by-id

in a hint box says:
> In HMS standard supports searching by ID but not at all, including : 
> - allergy
> - encounter
> - location
> - patient
> - practitioner

you mean that is a list we cannot request by id, right?

**Comment by HMSConnect** [comment]
@kopai-bmk , the domain resources in that list should work fine. 
But the old API(backend) doesn't support yet. I will update it.

Thank you for the issue.

**Comment by HMSConnect** [comment]
@kopai-bmk , Fixed on schema version "2.4.33".
Please help check again.

**Comment by HMSConnect** [comment]
@kopai-bmk , please wait, I fixed the old API but I need to check sandbox service first. I think sandbox service that wrapping on the old API need to change endpoint format. I will check it tomorrow.

**Comment by HMSConnect** [comment]
@kopai-bmk ,

Fixed, please try example below:

```js
hms.get('patient/MOCK-54569-4443', headers, null)
.then((response) => { console.log('Searching with request URL:', JSON.stringify(response, null, 2)); })
.catch((err) => { console.log('Error :', err); });
```
